version: "3"
services:
  app1: &app
    image: jndavidx/rinha-24-q1
    container_name: app1
    depends_on:
      - pg
    network_mode: host
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:)@127.0.0.1:5432/postgres
    deploy:
      resources:
        limits:
          cpus: "0.51"
          memory: 125M

  app2:
    <<: *app
    container_name: app2
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:)@127.0.0.1:5432/postgres
      - SERVER_PORT=8081

  nginx:
    image: nginx:1.25.4-alpine3.18-slim
    container_name: nginx
    depends_on:
      - app1
      - app2
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: 30M

  pg:
    image: postgres:16.2-alpine3.19
    container_name: pg
    restart: always
    command: postgres -c checkpoint_timeout=1h -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      - POSTGRES_PASSWORD=)
    network_mode: host
    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: 270M